'use strict';

// 城市/机场基础数据。coords 用于演示数据的距离估算。
const CITIES = [
  // ---- 国内 ----
  { code: 'PEK', city: '北京', en: 'Beijing', airport: '首都国际', lat: 40.08, lon: 116.59, hub: true, premium: true },
  { code: 'PKX', city: '北京', en: 'Beijing Daxing', airport: '大兴国际', lat: 39.51, lon: 116.41, hub: true, premium: true },
  { code: 'SHA', city: '上海', en: 'Shanghai', airport: '虹桥国际', lat: 31.2, lon: 121.34, hub: true, premium: true },
  { code: 'PVG', city: '上海', en: 'Shanghai Pudong', airport: '浦东国际', lat: 31.14, lon: 121.81, hub: true, premium: true },
  { code: 'CAN', city: '广州', en: 'Guangzhou', airport: '白云国际', lat: 23.39, lon: 113.3, hub: true, premium: true },
  { code: 'SZX', city: '深圳', en: 'Shenzhen', airport: '宝安国际', lat: 22.64, lon: 113.81, hub: true, premium: true },
  { code: 'CTU', city: '成都', en: 'Chengdu', airport: '双流国际', lat: 30.58, lon: 103.95, hub: true, premium: true },
  { code: 'TFU', city: '成都', en: 'Chengdu Tianfu', airport: '天府国际', lat: 30.32, lon: 104.44, hub: true, premium: true },
  { code: 'CKG', city: '重庆', en: 'Chongqing', airport: '江北国际', lat: 29.72, lon: 106.64, hub: true, premium: true },
  { code: 'XIY', city: '西安', en: 'Xian', airport: '咸阳国际', lat: 34.44, lon: 108.75, hub: true, premium: true },
  { code: 'KMG', city: '昆明', en: 'Kunming', airport: '长水国际', lat: 25.1, lon: 102.93, hub: true, premium: true },
  { code: 'WUH', city: '武汉', en: 'Wuhan', airport: '天河国际', lat: 30.78, lon: 114.21, hub: true, premium: true },
  { code: 'CSX', city: '长沙', en: 'Changsha', airport: '黄花国际', lat: 28.19, lon: 113.22, hub: true, premium: true },
  { code: 'HGH', city: '杭州', en: 'Hangzhou', airport: '萧山国际', lat: 30.23, lon: 120.43, hub: true, premium: true },
  { code: 'NKG', city: '南京', en: 'Nanjing', airport: '禄口国际', lat: 31.74, lon: 118.86, hub: true, premium: true },
  { code: 'TAO', city: '青岛', en: 'Qingdao', airport: '胶东国际', lat: 36.36, lon: 120.09, hub: true, premium: true },
  { code: 'XMN', city: '厦门', en: 'Xiamen', airport: '高崎国际', lat: 24.54, lon: 118.13, hub: true, premium: true },
  { code: 'FOC', city: '福州', en: 'Fuzhou', airport: '长乐国际', lat: 25.93, lon: 119.66, hub: true, premium: true },
  { code: 'CGO', city: '郑州', en: 'Zhengzhou', airport: '新郑国际', lat: 34.52, lon: 113.84, hub: true, premium: true },
  { code: 'TNA', city: '济南', en: 'Jinan', airport: '遥墙国际', lat: 36.86, lon: 117.22, hub: true },
  { code: 'TSN', city: '天津', en: 'Tianjin', airport: '滨海国际', lat: 39.12, lon: 117.35, hub: true, premium: true },
  { code: 'SHE', city: '沈阳', en: 'Shenyang', airport: '桃仙国际', lat: 41.64, lon: 123.48, hub: true, premium: true },
  { code: 'DLC', city: '大连', en: 'Dalian', airport: '周水子国际', lat: 38.97, lon: 121.54, hub: true, premium: true },
  { code: 'CGQ', city: '长春', en: 'Changchun', airport: '龙嘉国际', lat: 43.91, lon: 125.2, hub: true, premium: true },
  { code: 'HRB', city: '哈尔滨', en: 'Harbin', airport: '太平国际', lat: 45.62, lon: 126.25, hub: true, premium: true },
  { code: 'SYX', city: '三亚', en: 'Sanya', airport: '凤凰国际', lat: 18.3, lon: 109.41, hub: true, premium: true },
  { code: 'HAK', city: '海口', en: 'Haikou', airport: '美兰国际', lat: 19.93, lon: 110.46, hub: true, premium: true },
  { code: 'KWL', city: '桂林', en: 'Guilin', airport: '两江国际', lat: 25.22, lon: 110.04, hub: false },
  { code: 'NNG', city: '南宁', en: 'Nanning', airport: '吴圩国际', lat: 22.61, lon: 108.17, hub: true },
  { code: 'KWE', city: '贵阳', en: 'Guiyang', airport: '龙洞堡国际', lat: 26.54, lon: 106.8, hub: true },
  { code: 'TYN', city: '太原', en: 'Taiyuan', airport: '武宿国际', lat: 37.75, lon: 112.63, hub: false },
  { code: 'SJW', city: '石家庄', en: 'Shijiazhuang', airport: '正定国际', lat: 38.28, lon: 114.7, hub: false },
  { code: 'HET', city: '呼和浩特', en: 'Hohhot', airport: '白塔国际', lat: 40.85, lon: 111.82, hub: false },
  { code: 'LHW', city: '兰州', en: 'Lanzhou', airport: '中川国际', lat: 36.52, lon: 103.62, hub: true },
  { code: 'XNN', city: '西宁', en: 'Xining', airport: '曹家堡国际', lat: 36.53, lon: 102.04, hub: false },
  { code: 'INC', city: '银川', en: 'Yinchuan', airport: '河东国际', lat: 38.32, lon: 106.39, hub: false },
  { code: 'URC', city: '乌鲁木齐', en: 'Urumqi', airport: '地窝堡国际', lat: 43.91, lon: 87.47, hub: true, premium: true },
  { code: 'LXA', city: '拉萨', en: 'Lhasa', airport: '贡嘎国际', lat: 29.3, lon: 90.91, hub: false },
  { code: 'KHN', city: '南昌', en: 'Nanchang', airport: '昌北国际', lat: 28.86, lon: 115.9, hub: false },
  { code: 'HFE', city: '合肥', en: 'Hefei', airport: '新桥国际', lat: 31.99, lon: 116.97, hub: true },
  { code: 'WUX', city: '无锡', en: 'Wuxi', airport: '硕放国际', lat: 31.49, lon: 120.43, hub: false },
  { code: 'NGB', city: '宁波', en: 'Ningbo', airport: '栎社国际', lat: 29.83, lon: 121.46, hub: true },
  { code: 'WNZ', city: '温州', en: 'Wenzhou', airport: '龙湾国际', lat: 27.91, lon: 120.85, hub: true },
  { code: 'ZUH', city: '珠海', en: 'Zhuhai', airport: '金湾国际', lat: 22.01, lon: 113.38, hub: false },
  { code: 'LJG', city: '丽江', en: 'Lijiang', airport: '三义国际', lat: 26.68, lon: 100.25, hub: false },
  { code: 'DLU', city: '大理', en: 'Dali', airport: '凤仪机场', lat: 25.65, lon: 100.32, hub: false },
  { code: 'JHG', city: '西双版纳', en: 'Xishuangbanna', airport: '嘎洒国际', lat: 21.97, lon: 100.78, hub: false },
  { code: 'DYG', city: '张家界', en: 'Zhangjiajie', airport: '荷花国际', lat: 29.1, lon: 110.44, hub: false },
  { code: 'YIH', city: '宜昌', en: 'Yichang', airport: '三峡机场', lat: 30.56, lon: 111.48, hub: false },
  { code: 'XUZ', city: '徐州', en: 'Xuzhou', airport: '观音国际', lat: 34.06, lon: 117.55, hub: false },
  { code: 'NTG', city: '南通', en: 'Nantong', airport: '兴东国际', lat: 32.07, lon: 120.98, hub: false },
  { code: 'CZX', city: '常州', en: 'Changzhou', airport: '奔牛国际', lat: 31.92, lon: 119.78, hub: false },
  { code: 'YTY', city: '扬州', en: 'Yangzhou', airport: '泰州国际', lat: 32.56, lon: 119.72, hub: false },
  { code: 'YNZ', city: '盐城', en: 'Yancheng', airport: '南洋国际', lat: 33.43, lon: 120.16, hub: false },
  { code: 'LYG', city: '连云港', en: 'Lianyungang', airport: '花果山国际', lat: 34.55, lon: 119.13, hub: false },
  { code: 'HIA', city: '淮安', en: "Huai'an", airport: '涟水国际', lat: 33.78, lon: 119.13, hub: false },
  { code: 'YIW', city: '义乌', en: 'Yiwu', airport: '义乌机场', lat: 29.34, lon: 120.07, hub: false },
  { code: 'HSN', city: '舟山', en: 'Zhoushan', airport: '普陀山机场', lat: 29.93, lon: 122.36, hub: false },
  { code: 'HYN', city: '台州', en: 'Taizhou', airport: '路桥机场', lat: 28.56, lon: 121.43, hub: false },
  { code: 'JJN', city: '泉州', en: 'Quanzhou', airport: '晋江国际', lat: 24.8, lon: 118.59, hub: false },
  { code: 'SWA', city: '汕头', en: 'Shantou', airport: '潮汕国际', lat: 23.55, lon: 116.51, hub: false },
  { code: 'ZHA', city: '湛江', en: 'Zhanjiang', airport: '吴川机场', lat: 21.48, lon: 110.59, hub: false },
  { code: 'BHY', city: '北海', en: 'Beihai', airport: '福成机场', lat: 21.54, lon: 109.29, hub: false },
  { code: 'LZH', city: '柳州', en: 'Liuzhou', airport: '白莲机场', lat: 24.19, lon: 109.39, hub: false },
  { code: 'DSN', city: '鄂尔多斯', en: 'Ordos', airport: '伊金霍洛国际', lat: 39.49, lon: 109.86, hub: false },
  { code: 'BAV', city: '包头', en: 'Baotou', airport: '东河机场', lat: 40.56, lon: 109.99, hub: false },
  { code: 'YNT', city: '烟台', en: 'Yantai', airport: '蓬莱国际', lat: 37.4, lon: 121.37, hub: false },
  { code: 'WEH', city: '威海', en: 'Weihai', airport: '大水泊国际', lat: 37.19, lon: 122.23, hub: false },
  { code: 'LYA', city: '洛阳', en: 'Luoyang', airport: '北郊机场', lat: 34.74, lon: 112.39, hub: false },
  { code: 'XFN', city: '襄阳', en: 'Xiangyang', airport: '刘集机场', lat: 32.15, lon: 112.29, hub: false },
  { code: 'ZYI', city: '遵义', en: 'Zunyi', airport: '新舟机场', lat: 27.8, lon: 107.24, hub: false },
  { code: 'MIG', city: '绵阳', en: 'Mianyang', airport: '南郊机场', lat: 31.43, lon: 104.74, hub: false },
  { code: 'NAO', city: '南充', en: 'Nanchong', airport: '高坪机场', lat: 30.8, lon: 106.16, hub: false },
  { code: 'YIN', city: '伊宁', en: 'Yining', airport: '伊宁机场', lat: 43.96, lon: 81.33, hub: false },
  { code: 'BNE', city: '布里斯班', en: 'Brisbane', airport: '布里斯班国际', lat: -27.38, lon: 153.12, hub: true },
  { code: 'OOL', city: '黄金海岸', en: 'Gold Coast', airport: '黄金海岸机场', lat: -28.16, lon: 153.51, hub: false },
  { code: 'CNS', city: '凯恩斯', en: 'Cairns', airport: '凯恩斯国际', lat: -16.89, lon: 145.76, hub: false },
  { code: 'MIA', city: '迈阿密', en: 'Miami', airport: '迈阿密国际', lat: 25.79, lon: -80.29, hub: true },
  { code: 'ATL', city: '亚特兰大', en: 'Atlanta', airport: '哈茨菲尔德-杰克逊国际', lat: 33.64, lon: -84.43, hub: true },
  { code: 'LAS', city: '拉斯维加斯', en: 'Las Vegas', airport: '麦卡伦国际', lat: 36.08, lon: -115.15, hub: true },
  { code: 'PHX', city: '凤凰城', en: 'Phoenix', airport: '天港国际', lat: 33.43, lon: -112.01, hub: true },
  { code: 'YOW', city: '渥太华', en: 'Ottawa', airport: '渥太华国际', lat: 45.32, lon: -75.67, hub: false },
  { code: 'YMQ', city: '蒙特利尔', en: 'Montreal', airport: '特鲁多国际', lat: 45.47, lon: -73.74, hub: true },
  { code: 'LED', city: '圣彼得堡', en: 'St Petersburg', airport: '普尔科沃国际', lat: 59.8, lon: 30.26, hub: true },
  // ---- 国际/地区 ----
  { code: 'HND', city: '东京', en: 'Tokyo Haneda', airport: '羽田国际', lat: 35.55, lon: 139.78, hub: true, premium: true },
  { code: 'NRT', city: '东京', en: 'Tokyo Narita', airport: '成田国际', lat: 35.77, lon: 140.39, hub: true, premium: true },
  { code: 'KIX', city: '大阪', en: 'Osaka', airport: '关西国际', lat: 34.43, lon: 135.23, hub: true, premium: true },
  { code: 'ICN', city: '首尔', en: 'Seoul', airport: '仁川国际', lat: 37.46, lon: 126.44, hub: true, premium: true },
  { code: 'BKK', city: '曼谷', en: 'Bangkok', airport: '素万那普国际', lat: 13.69, lon: 100.75, hub: true, premium: true },
  { code: 'SIN', city: '新加坡', en: 'Singapore', airport: '樟宜国际', lat: 1.36, lon: 103.99, hub: true, premium: true },
  { code: 'KUL', city: '吉隆坡', en: 'Kuala Lumpur', airport: '吉隆坡国际', lat: 2.75, lon: 101.71, hub: true, premium: true },
  { code: 'MNL', city: '马尼拉', en: 'Manila', airport: '尼诺伊·阿基诺国际', lat: 14.51, lon: 121.02, hub: true },
  { code: 'CGK', city: '雅加达', en: 'Jakarta', airport: '苏加诺-哈达国际', lat: -6.13, lon: 106.66, hub: true },
  { code: 'SGN', city: '胡志明市', en: 'Ho Chi Minh City', airport: '新山一国际', lat: 10.82, lon: 106.66, hub: true },
  { code: 'HAN', city: '河内', en: 'Hanoi', airport: '内排国际', lat: 21.22, lon: 105.8, hub: true },
  { code: 'PNH', city: '金边', en: 'Phnom Penh', airport: '金边国际', lat: 11.55, lon: 104.84, hub: false },
  { code: 'VTE', city: '万象', en: 'Vientiane', airport: '瓦岱国际', lat: 18.0, lon: 102.56, hub: false },
  { code: 'HKG', city: '香港', en: 'Hong Kong', airport: '香港国际', lat: 22.31, lon: 113.91, hub: true, premium: true },
  { code: 'MFM', city: '澳门', en: 'Macau', airport: '澳门国际', lat: 22.15, lon: 113.59, hub: true },
  { code: 'TPE', city: '台北', en: 'Taipei', airport: '桃园国际', lat: 25.08, lon: 121.23, hub: true, premium: true },
  { code: 'SYD', city: '悉尼', en: 'Sydney', airport: '金斯福德·史密斯国际', lat: -33.95, lon: 151.18, hub: true, premium: true },
  { code: 'MEL', city: '墨尔本', en: 'Melbourne', airport: '图拉马林国际', lat: -37.67, lon: 144.84, hub: true, premium: true },
  { code: 'AKL', city: '奥克兰', en: 'Auckland', airport: '奥克兰国际', lat: -37.01, lon: 174.79, hub: true, premium: true },
  { code: 'LHR', city: '伦敦', en: 'London', airport: '希思罗国际', lat: 51.47, lon: -0.45, hub: true, premium: true },
  { code: 'CDG', city: '巴黎', en: 'Paris', airport: '戴高乐国际', lat: 49.01, lon: 2.55, hub: true, premium: true },
  { code: 'FRA', city: '法兰克福', en: 'Frankfurt', airport: '法兰克福国际', lat: 50.03, lon: 8.56, hub: true, premium: true },
  { code: 'AMS', city: '阿姆斯特丹', en: 'Amsterdam', airport: '史基浦国际', lat: 52.31, lon: 4.76, hub: true, premium: true },
  { code: 'MAD', city: '马德里', en: 'Madrid', airport: '巴拉哈斯国际', lat: 40.47, lon: -3.56, hub: true },
  { code: 'MXP', city: '米兰', en: 'Milan', airport: '马尔彭萨国际', lat: 45.63, lon: 8.72, hub: true },
  { code: 'MUC', city: '慕尼黑', en: 'Munich', airport: '慕尼黑国际', lat: 48.35, lon: 11.79, hub: true },
  { code: 'ZRH', city: '苏黎世', en: 'Zurich', airport: '苏黎世国际', lat: 47.46, lon: 8.55, hub: true },
  { code: 'VIE', city: '维也纳', en: 'Vienna', airport: '维也纳国际', lat: 48.11, lon: 16.57, hub: true },
  { code: 'DUB', city: '都柏林', en: 'Dublin', airport: '都柏林国际', lat: 53.43, lon: -6.25, hub: false },
  { code: 'SVO', city: '莫斯科', en: 'Moscow', airport: '谢列梅捷沃国际', lat: 55.97, lon: 37.41, hub: true },
  { code: 'IST', city: '伊斯坦布尔', en: 'Istanbul', airport: '伊斯坦布尔国际', lat: 41.26, lon: 28.74, hub: true },
  { code: 'DXB', city: '迪拜', en: 'Dubai', airport: '迪拜国际', lat: 25.25, lon: 55.36, hub: true, premium: true },
  { code: 'DEL', city: '德里', en: 'Delhi', airport: '英迪拉·甘地国际', lat: 28.56, lon: 77.1, hub: true },
  { code: 'BOM', city: '孟买', en: 'Mumbai', airport: '贾特拉帕蒂·希瓦吉国际', lat: 19.09, lon: 72.87, hub: true },
  { code: 'KTM', city: '加德满都', en: 'Kathmandu', airport: '特里布万国际', lat: 27.7, lon: 85.36, hub: false },
  { code: 'CMB', city: '科伦坡', en: 'Colombo', airport: '班达拉奈克国际', lat: 7.18, lon: 79.88, hub: false },
  { code: 'MLE', city: '马累', en: 'Male', airport: '马累国际', lat: 4.19, lon: 73.53, hub: false },
  { code: 'JFK', city: '纽约', en: 'New York', airport: '肯尼迪国际', lat: 40.64, lon: -73.78, hub: true, premium: true },
  { code: 'EWR', city: '纽约', en: 'Newark', airport: '纽瓦克国际', lat: 40.69, lon: -74.17, hub: true, premium: true },
  { code: 'BOS', city: '波士顿', en: 'Boston', airport: '洛根国际', lat: 42.36, lon: -71.01, hub: false },
  { code: 'IAD', city: '华盛顿', en: 'Washington', airport: '杜勒斯国际', lat: 38.95, lon: -77.46, hub: false },
  { code: 'PHL', city: '费城', en: 'Philadelphia', airport: '费城国际', lat: 39.87, lon: -75.24, hub: false },
  { code: 'LAX', city: '洛杉矶', en: 'Los Angeles', airport: '洛杉矶国际', lat: 33.94, lon: -118.41, hub: true, premium: true },
  { code: 'SFO', city: '旧金山', en: 'San Francisco', airport: '旧金山国际', lat: 37.62, lon: -122.38, hub: true, premium: true },
  { code: 'SEA', city: '西雅图', en: 'Seattle', airport: '西雅图-塔科马国际', lat: 47.45, lon: -122.31, hub: true },
  { code: 'ORD', city: '芝加哥', en: 'Chicago', airport: '奥黑尔国际', lat: 41.97, lon: -87.91, hub: true },
  { code: 'YVR', city: '温哥华', en: 'Vancouver', airport: '温哥华国际', lat: 49.19, lon: -123.18, hub: true, premium: true },
  { code: 'YYZ', city: '多伦多', en: 'Toronto', airport: '皮尔逊国际', lat: 43.68, lon: -79.63, hub: true },
];

const BY_CODE = new Map(CITIES.map((c) => [c.code, c]));

function findCity(query) {
  const q = String(query || '').trim().toLowerCase();
  if (!q) return [];
  const direct = BY_CODE.get(q.toUpperCase());
  if (direct) return [direct];
  return CITIES.filter((c) =>
    c.city.includes(q) ||
    c.en.toLowerCase().includes(q) ||
    c.airport.toLowerCase().includes(q) ||
    c.code.toLowerCase() === q
  );
}

function getCity(code) {
  return BY_CODE.get(String(code || '').toUpperCase()) || null;
}

// 经停目的地 D 之后常见的“续程尾巴”候选（用于甩尾方案搜索）
const CONTINUATIONS = {
  PEK: ['CGQ', 'HRB', 'SHE', 'DLC', 'TAO', 'URC', 'YNT', 'HET', 'TYN', 'INC'],
  PKX: ['CGQ', 'HRB', 'SHE', 'DLC', 'TAO', 'URC', 'YNT'],
  SHA: ['HGH', 'NGB', 'WNZ', 'TAO', 'XMN', 'YNT', 'WEH'],
  PVG: ['HGH', 'NGB', 'WNZ', 'TAO', 'XMN', 'YIW', 'HSN'],
  CAN: ['SZX', 'HAK', 'KWL', 'BHY', 'ZHA', 'SWA', 'XMN', 'SYX'],
  SZX: ['HAK', 'KWL', 'BHY', 'ZHA', 'SYX', 'SWA', 'NNG'],
  CTU: ['CKG', 'XNN', 'LHW', 'LJG', 'DYG', 'ZYI', 'INC'],
  TFU: ['CKG', 'XNN', 'LHW', 'LJG', 'ZYI', 'INC'],
  CKG: ['XNN', 'LHW', 'LJG', 'ZYI', 'DYG', 'KWE'],
  XIY: ['LHW', 'XNN', 'INC', 'URC', 'YIN', 'TYN', 'HET'],
  KMG: ['LJG', 'DLU', 'JHG', 'ZYI', 'KWE', 'LXA'],
  WUH: ['YIH', 'XFN', 'DYG', 'KWL', 'NNG'],
  CSX: ['DYG', 'ZYI', 'KWL', 'LJG', 'JHG'],
  HGH: ['WNZ', 'NGB', 'YIW', 'HSN', 'LJG', 'FOC'],
  NKG: ['NTG', 'XUZ', 'LYG', 'HIA', 'YTY', 'CZX', 'YNZ'],
  TAO: ['YNT', 'WEH', 'DLC', 'LJG', 'XUZ', 'LYG'],
  XMN: ['JJN', 'FOC', 'WNZ', 'KWL', 'SWA', 'NNG'],
  FOC: ['JJN', 'WNZ', 'XMN', 'KWL', 'SWA'],
  CGO: ['LYA', 'XFN', 'YIH', 'XUZ', 'HIA'],
  TNA: ['YNT', 'WEH', 'XUZ', 'LYG', 'HIA'],
  TSN: ['DLC', 'YNT', 'WEH', 'SJW', 'CGQ', 'SHE'],
  SHE: ['DLC', 'CGQ', 'HRB', 'TAO', 'YNT', 'WEH'],
  DLC: ['YNT', 'WEH', 'TAO', 'CGQ', 'HRB'],
  CGQ: ['HRB', 'SHE', 'DLC', 'TAO', 'YNT'],
  HRB: ['CGQ', 'SHE', 'DLC', 'TAO', 'YNT', 'WEH'],
  HAK: ['SYX', 'BHY', 'KWL', 'NNG', 'ZHA'],
  SYX: ['HAK', 'BHY', 'NNG', 'KWL'],
  URC: ['LHW', 'INC', 'XNN', 'TYN', 'HET'],
  LHW: ['XNN', 'INC', 'URC', 'TYN', 'HET'],
  NNG: ['BHY', 'KWL', 'ZHA', 'SYX', 'HAK'],
  KWE: ['ZYI', 'KWL', 'LJG', 'XNN', 'LHW'],
  HKG: ['TPE', 'KIX', 'NRT', 'HND', 'BKK', 'SIN', 'MNL', 'KUL'],
  TPE: ['KIX', 'NRT', 'HND', 'HKG', 'BKK', 'SGN'],
  ICN: ['HND', 'NRT', 'KIX', 'BKK', 'SIN', 'TPE'],
  BKK: ['SIN', 'KUL', 'MNL', 'SGN', 'HAN', 'PNH', 'MLE', 'CMB'],
  SIN: ['KUL', 'CGK', 'MNL', 'BKK', 'SGN', 'PNH'],
  KUL: ['SIN', 'BKK', 'SGN', 'PNH', 'MLE'],
  NRT: ['KIX', 'TPE', 'ICN', 'HKG', 'BKK', 'SIN'],
  HND: ['KIX', 'TPE', 'ICN', 'HKG', 'BKK'],
  KIX: ['NRT', 'HND', 'TPE', 'HKG', 'ICN', 'BKK'],
  SYD: ['MEL', 'AKL', 'BNE', 'OOL', 'CNS'],
  MEL: ['SYD', 'AKL', 'BNE', 'OOL'],
  AKL: ['SYD', 'MEL', 'BNE'],
  LHR: ['CDG', 'AMS', 'FRA', 'DUB', 'MAD', 'MUC', 'ZRH', 'VIE'],
  CDG: ['AMS', 'FRA', 'LHR', 'MAD', 'MXP', 'MUC', 'ZRH', 'DUB'],
  FRA: ['AMS', 'CDG', 'LHR', 'MUC', 'ZRH', 'VIE', 'MAD', 'MXP'],
  AMS: ['CDG', 'FRA', 'LHR', 'MUC', 'ZRH', 'VIE', 'DUB'],
  MAD: ['MXP', 'FRA', 'CDG', 'AMS', 'DUB'],
  MXP: ['FRA', 'CDG', 'AMS', 'MAD', 'ZRH'],
  MUC: ['FRA', 'AMS', 'CDG', 'ZRH', 'VIE'],
  ZRH: ['FRA', 'MUC', 'VIE', 'CDG', 'AMS'],
  VIE: ['MUC', 'ZRH', 'FRA', 'AMS', 'CDG'],
  DXB: ['SIN', 'BKK', 'KUL', 'HKG', 'DEL', 'BOM', 'CMB', 'MLE'],
  DEL: ['BOM', 'KTM', 'CMB', 'MLE', 'SIN', 'BKK'],
  BOM: ['DEL', 'CMB', 'MLE', 'SIN', 'BKK'],
  JFK: ['BOS', 'IAD', 'PHL', 'ORD', 'MIA', 'ATL'],
  EWR: ['BOS', 'IAD', 'PHL', 'ORD', 'MIA', 'ATL'],
  BOS: ['IAD', 'PHL', 'ORD', 'JFK'],
  IAD: ['BOS', 'PHL', 'ORD', 'JFK'],
  PHL: ['BOS', 'IAD', 'ORD', 'JFK'],
  LAX: ['SFO', 'SEA', 'ORD', 'YVR', 'LAS', 'PHX'],
  SFO: ['SEA', 'LAX', 'YVR', 'ORD', 'LAS'],
  SEA: ['SFO', 'LAX', 'YVR', 'ORD', 'LAS'],
  ORD: ['BOS', 'IAD', 'PHL', 'MIA', 'ATL'],
  YVR: ['SEA', 'SFO', 'LAX', 'YYZ', 'YOW'],
  YYZ: ['YVR', 'YOW', 'YMQ', 'BOS', 'ORD'],
  SVO: ['LED', 'IST', 'DXB', 'BKK'],
  IST: ['DXB', 'LHR', 'CDG', 'FRA', 'SVO'],
};

// 未在表内时用的兜底续程
const FALLBACK_TAILS = ['PEK', 'SHA', 'PVG', 'CAN', 'SZX', 'CTU', 'XIY', 'HGH', 'NGB', 'TAO', 'XMN', 'CGQ', 'HRB', 'SHE', 'DLC', 'HAK', 'SYX'];

function continuationsFor(code) {
  return CONTINUATIONS[code] || FALLBACK_TAILS;
}

// 国际续程尾巴：用于“国内飞国内甩国际段 / 国际飞国际同理”的甩尾检测。
// 国内枢纽 → 可甩的国际段；国际枢纽 → 更丰富的国际续程。
const INT_CONTINUATIONS = {
  PEK: ['NRT', 'HND', 'ICN', 'BKK', 'SIN', 'HKG', 'TPE', 'LHR', 'CDG', 'FRA', 'LAX', 'SFO', 'SYD', 'DXB', 'MUC', 'AMS'],
  PKX: ['NRT', 'ICN', 'BKK', 'SIN', 'HKG', 'TPE', 'LHR', 'FRA', 'LAX', 'SYD'],
  SHA: ['NRT', 'HND', 'ICN', 'BKK', 'SIN', 'HKG', 'TPE', 'SYD', 'LAX', 'LHR', 'CDG', 'SFO'],
  PVG: ['NRT', 'HND', 'ICN', 'BKK', 'SIN', 'HKG', 'TPE', 'SYD', 'LAX', 'LHR', 'CDG', 'FRA'],
  CAN: ['NRT', 'KIX', 'ICN', 'BKK', 'SIN', 'HKG', 'TPE', 'SYD', 'LAX', 'LHR', 'SFO'],
  SZX: ['NRT', 'KIX', 'BKK', 'SIN', 'HKG', 'TPE', 'ICN', 'SYD'],
  CTU: ['HKG', 'TPE', 'BKK', 'ICN', 'NRT', 'SIN', 'LHR'],
  TFU: ['HKG', 'TPE', 'BKK', 'ICN', 'NRT', 'SIN'],
  CKG: ['HKG', 'BKK', 'SIN', 'TPE', 'ICN', 'NRT'],
  XIY: ['HKG', 'TPE', 'BKK', 'ICN', 'NRT'],
  KMG: ['HKG', 'BKK', 'SIN', 'TPE', 'ICN'],
  WUH: ['HKG', 'TPE', 'BKK', 'ICN', 'SIN'],
  CSX: ['HKG', 'TPE', 'BKK', 'SIN'],
  HGH: ['HKG', 'TPE', 'BKK', 'ICN', 'NRT', 'SIN'],
  NKG: ['HKG', 'TPE', 'BKK', 'ICN', 'NRT', 'SIN'],
  TAO: ['HKG', 'TPE', 'BKK', 'ICN', 'NRT'],
  XMN: ['HKG', 'TPE', 'BKK', 'SIN', 'ICN'],
  FOC: ['HKG', 'TPE', 'BKK', 'SIN'],
  CGO: ['HKG', 'TPE', 'BKK', 'ICN'],
  TSN: ['HKG', 'TPE', 'ICN', 'BKK', 'NRT'],
  SHE: ['HKG', 'TPE', 'ICN', 'BKK', 'NRT'],
  DLC: ['HKG', 'TPE', 'ICN', 'BKK'],
  CGQ: ['HKG', 'TPE', 'ICN', 'BKK'],
  HRB: ['HKG', 'TPE', 'ICN', 'BKK', 'NRT'],
  HAK: ['HKG', 'TPE', 'BKK', 'SIN', 'ICN'],
  SYX: ['HKG', 'TPE', 'BKK', 'SIN', 'ICN'],
  URC: ['HKG', 'BKK', 'ICN'],
  HKG: ['TPE', 'KIX', 'NRT', 'HND', 'BKK', 'SIN', 'MNL', 'KUL', 'SGN', 'HAN', 'DXB', 'SYD', 'MEL', 'LHR', 'CDG', 'FRA', 'LAX', 'SFO', 'YVR'],
  TPE: ['KIX', 'NRT', 'HND', 'HKG', 'BKK', 'SGN', 'SIN', 'KUL', 'MNL', 'ICN', 'LAX', 'SFO', 'SYD'],
  ICN: ['HND', 'NRT', 'KIX', 'BKK', 'SIN', 'TPE', 'HKG', 'SGN', 'KUL', 'LAX', 'SFO', 'SYD', 'LHR', 'CDG'],
  BKK: ['SIN', 'KUL', 'MNL', 'SGN', 'HAN', 'PNH', 'MLE', 'CMB', 'HKG', 'TPE', 'ICN', 'NRT', 'HND', 'KIX', 'DXB', 'SYD'],
  SIN: ['KUL', 'CGK', 'MNL', 'BKK', 'SGN', 'PNH', 'HKG', 'TPE', 'ICN', 'NRT', 'HND', 'KIX', 'DXB', 'SYD', 'MEL', 'LHR', 'CDG'],
  NRT: ['KIX', 'TPE', 'ICN', 'HKG', 'BKK', 'SIN', 'KUL', 'SGN', 'LAX', 'SFO', 'SYD', 'LHR', 'CDG'],
  HND: ['KIX', 'TPE', 'ICN', 'HKG', 'BKK', 'SIN', 'LAX', 'SFO', 'SYD'],
  KIX: ['NRT', 'HND', 'TPE', 'HKG', 'ICN', 'BKK', 'SIN', 'SGN', 'LAX'],
  SYD: ['MEL', 'AKL', 'BNE', 'OOL', 'CNS', 'SIN', 'BKK', 'HKG', 'NRT', 'HND', 'KIX', 'LAX', 'SFO', 'LHR'],
  MEL: ['SYD', 'AKL', 'BNE', 'SIN', 'BKK', 'HKG', 'NRT', 'LAX', 'LHR'],
  LHR: ['CDG', 'AMS', 'FRA', 'DUB', 'MAD', 'MUC', 'ZRH', 'VIE', 'JFK', 'LAX', 'SFO', 'DXB', 'SIN', 'HKG', 'NRT'],
  CDG: ['AMS', 'FRA', 'LHR', 'MAD', 'MXP', 'MUC', 'ZRH', 'JFK', 'LAX', 'DXB', 'BKK', 'SIN', 'NRT'],
  FRA: ['AMS', 'CDG', 'LHR', 'MUC', 'ZRH', 'VIE', 'MAD', 'MXP', 'JFK', 'LAX', 'SFO', 'DXB', 'BKK', 'SIN', 'NRT', 'ICN'],
  AMS: ['CDG', 'FRA', 'LHR', 'MUC', 'ZRH', 'VIE', 'DUB', 'JFK', 'LAX', 'DXB', 'BKK', 'SIN'],
  DXB: ['SIN', 'BKK', 'KUL', 'HKG', 'DEL', 'BOM', 'CMB', 'MLE', 'LHR', 'CDG', 'FRA', 'JFK', 'SYD', 'NRT'],
  JFK: ['BOS', 'IAD', 'PHL', 'ORD', 'MIA', 'ATL', 'LHR', 'CDG', 'FRA', 'DXB', 'ICN', 'NRT', 'SIN'],
  LAX: ['SFO', 'SEA', 'ORD', 'YVR', 'LAS', 'PHX', 'NRT', 'HND', 'ICN', 'SIN', 'BKK', 'SYD', 'MEL', 'LHR', 'CDG'],
  SFO: ['SEA', 'LAX', 'YVR', 'ORD', 'LAS', 'NRT', 'HND', 'ICN', 'SIN', 'SYD', 'LHR'],
  YVR: ['SEA', 'SFO', 'LAX', 'YYZ', 'YOW', 'NRT', 'HND', 'ICN', 'SIN', 'SYD', 'LHR'],
};

function internationalTailsFor(code) {
  return INT_CONTINUATIONS[code] || [];
}

const AIRLINE_NAMES = {
  CA: '国航', CZ: '南航', MU: '东航', HU: '海航', '3U': '川航', MF: '厦航',
  ZH: '深航', SC: '山航', HO: '吉祥', '9C': '春秋', GS: '天津航', '8L': '祥鹏',
  KN: '中联航', FM: '上航', JD: '首都航', PN: '西部航', KY: '昆明航', QW: '青岛航',
  CX: '国泰', KA: '港龙', BR: '长荣', CI: '华航', KE: '大韩', OZ: '韩亚',
  NH: '全日空', JL: '日航', TG: '泰航', SQ: '新航', MH: '马航', AK: '亚航',
  BA: '英航', AF: '法航', LH: '汉莎', EK: '阿联酋', UA: '美联航', AA: '美航',
  AC: '加航', QF: '澳航', NZ: '纽航', DL: '达美', LX: '瑞航', OS: '奥航',
  KL: '荷航', IB: '伊比利亚', SU: '俄航', TK: '土航', AI: '印度航空', GA: '鹰航',
  VS: '维珍航空', PR: '菲律宾航空', VN: '越南航空', OQ: '重庆航空', SC: '山航',
};

const HUB_AIRLINES = {
  PEK: ['CA', 'HU', 'KN', 'MU', 'CZ'],
  PKX: ['CA', 'MU', 'CZ', 'KN'],
  SHA: ['MU', 'FM', 'HO', 'CA', '9C', 'CZ'],
  PVG: ['MU', 'FM', '9C', 'HO', 'CA', 'CZ'],
  CAN: ['CZ', 'CA', 'MU', 'HU', '3U'],
  SZX: ['ZH', 'CZ', 'HU', 'MU', 'CA'],
  CTU: ['3U', 'CA', 'MU', 'CZ'],
  TFU: ['3U', 'CA', 'CZ', 'MU'],
  CKG: ['3U', 'CA', 'CZ', 'HU'],
  XIY: ['MU', 'HU', 'GS', 'CA', 'CZ'],
  KMG: ['MU', '8L', 'KY', 'CA', '3U'],
  WUH: ['CZ', 'MU', 'HU', 'CA'],
  CSX: ['HU', 'MU', 'CZ', 'CA'],
  HGH: ['HU', 'MU', 'CZ', '9C', 'CA'],
  NKG: ['MU', 'HO', 'ZH', 'CZ'],
  TAO: ['SC', 'MU', 'CZ', 'QW'],
  XMN: ['MF', 'CZ', 'MU', 'CA'],
  FOC: ['MF', 'MU', 'CA'],
  CGO: ['HU', 'CZ', '9C', 'MU'],
  TNA: ['SC', 'MU', 'CZ'],
  TSN: ['GS', 'CA', 'MU', 'OQ'],
  SHE: ['CZ', 'CA', 'MU', '9C'],
  DLC: ['CZ', 'HU', 'CA', 'MU'],
  CGQ: ['CZ', 'CA', 'MU', 'HU'],
  HRB: ['CZ', 'CA', 'MU', '3U'],
  HAK: ['HU', 'CZ', '9C', 'MU'],
  SYX: ['CZ', 'HU', '9C', 'MU'],
  URC: ['CZ', 'HU', 'GS', 'CA'],
  LHW: ['MU', 'HU', '9C'],
  KWE: ['CA', 'CZ', '3U'],
  HKG: ['CX', 'KA', 'MU', 'CA', 'CZ'],
  TPE: ['BR', 'CI', 'CZ', 'MU', 'CA'],
  ICN: ['KE', 'OZ', 'MU', 'CZ', 'CA'],
  HND: ['NH', 'JL', 'MU', 'CA'],
  NRT: ['NH', 'JL', 'MU', 'CA', 'CZ'],
  KIX: ['NH', 'JL', 'CZ', 'MU', 'CA'],
  BKK: ['TG', 'MU', 'CZ', '3U', 'CA'],
  SIN: ['SQ', 'MU', 'CZ', 'CA', '3U'],
  KUL: ['MH', 'AK', 'CZ', 'MU'],
  MNL: ['PR', 'CZ', 'MU'],
  CGK: ['GA', 'CZ', 'MU'],
  SGN: ['VN', 'CZ', 'MU'],
  HAN: ['VN', 'CZ', 'MU'],
  SYD: ['QF', 'MU', 'CZ', 'CA'],
  MEL: ['QF', 'MU', 'CZ'],
  AKL: ['NZ', 'MU', 'CA'],
  LHR: ['BA', 'CA', 'MU', 'CZ', 'VS'],
  CDG: ['AF', 'MU', 'CA', 'CZ'],
  FRA: ['LH', 'CA', 'MU'],
  AMS: ['KL', 'MU', 'CZ'],
  MAD: ['IB', 'MU', 'CA'],
  MXP: ['LH', 'AF', 'MU', 'CA'],
  MUC: ['LH', 'CA', 'MU'],
  ZRH: ['LX', 'CA', 'MU'],
  VIE: ['OS', 'CA', 'MU'],
  DXB: ['EK', 'CZ', 'MU', 'CA'],
  DEL: ['AI', 'CZ', 'MU', 'CA'],
  BOM: ['AI', 'CZ', 'MU'],
  JFK: ['UA', 'AA', 'MU', 'CA', 'CZ'],
  EWR: ['UA', 'CA', 'MU'],
  LAX: ['UA', 'AA', 'CA', 'MU', 'CZ'],
  SFO: ['UA', 'CA', 'MU'],
  SEA: ['DL', 'HU', 'CA'],
  ORD: ['UA', 'AA', 'CA', 'MU'],
  YVR: ['AC', 'MU', 'CA', 'CZ'],
  YYZ: ['AC', 'MU', 'CA'],
  SVO: ['SU', 'CZ', 'HU'],
  IST: ['TK', 'CA', 'MU'],
};

const DEFAULT_AIRLINES = ['CA', 'CZ', 'MU', 'HU', '3U', 'MF', 'ZH', 'HO', '9C', 'GS'];

function airlinesFor(code) {
  return HUB_AIRLINES[code] || DEFAULT_AIRLINES;
}

function isDomestic(a, b) {
  const domestic = new Set(['PEK', 'PKX', 'SHA', 'PVG', 'CAN', 'SZX', 'CTU', 'TFU', 'CKG', 'XIY', 'KMG', 'WUH', 'CSX', 'HGH', 'NKG', 'TAO', 'XMN', 'FOC', 'CGO', 'TNA', 'TSN', 'SHE', 'DLC', 'CGQ', 'HRB', 'SYX', 'HAK', 'KWL', 'NNG', 'KWE', 'TYN', 'SJW', 'HET', 'LHW', 'XNN', 'INC', 'URC', 'LXA', 'KHN', 'HFE', 'WUX', 'NGB', 'WNZ', 'ZUH', 'LJG', 'DLU', 'JHG', 'DYG', 'YIH', 'XUZ', 'NTG', 'CZX', 'YTY', 'YNZ', 'LYG', 'HIA', 'YIW', 'HSN', 'HYN', 'JJN', 'SWA', 'ZHA', 'BHY', 'LZH', 'DSN', 'BAV', 'YNT', 'WEH', 'LYA', 'XFN', 'ZYI', 'MIG', 'NAO']);
  return domestic.has(a) && domestic.has(b);
}

function haversineKm(a, b) {
  const R = 6371;
  const rad = (d) => (d * Math.PI) / 180;
  const dLat = rad(b.lat - a.lat);
  const dLon = rad(b.lon - a.lon);
  const s = Math.sin(dLat / 2) ** 2 + Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}

module.exports = {
  CITIES,
  findCity,
  getCity,
  continuationsFor,
  airlinesFor,
  airlineName: (code) => AIRLINE_NAMES[code] || code,
  isDomestic,
  haversineKm,
  internationalTailsFor,
};
